### PR TITLE
Add node_access_rebuild() to hostmaster.install

### PR DESCRIPTION
**Pull request by jonpugh**
At the end of every Aegir install, you are confronted with a message:

screen shot 2016-07-28 at 10 26 34 am

> The content access permissions need to be rebuilt.

Turns out this was in place for aegir 1.x and 2.x.  I finally tracked down where it was removed: https://github.com/aegir-project/hostmaster/commit/8d4798fc6ea94fce1f333724b09d045699160d7d#diff-1b4732042832a44c3aa98e72063a3e67  https://www.drupal.org/node/2041911

Taking this opportunity to make our first pull request.

### CODE REVIEW

**Comment by helmo** [comment]
@jonpugh is there a way to re-test this without adding a commit?

**Comment by jonpugh** [comment]
@helmo Just visit the "Details" page linked to in the Checks section, it will take you to the http://travis-ci.org page for the specific build.

Log in with github, and visit the build page again, there should be a "Reload" button (a circular arrow graphic) to restart the build.

**Comment by helmo** [comment]
Strange ... I don't see that button like on  like http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit 

selection_050

**Comment by helmo** [comment]
After I disabled and enabled the travis integration on https://github.com/aegir-project/hostmaster/settings/hooks/9298439 I could see the restart icon... so I clicked.

YAY

**Pull request merged**
